name: "Parrix infra pipeline"
on: 
  workflow_dispatch:
    inputs:
      working_directory:
        description: "Path to Terraform working directory"
        required: true
        default: "rg"
        
permissions:
  id-token: write
  contents: read        

jobs:
  terraform:
    name: Terraform on Windows Self-Hosted Runner
    runs-on: [self-hosted, Windows]

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_IN_AUTOMATION: true
      TF_INPUT: false
      WORK_DIR: ${{ github.event.inputs.working_directory }}

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      # 2️⃣ Verify working directory
      - name: Verify working directory
        run: |
          Get-ChildItem ${{ github.workspace }}

      # 3️⃣ Terraform Init
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ github.workspace }}/{{ github.event.inputs.working_directory }}

      # 4️⃣ Terraform Validate
      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ${{ github.workspace }}/{{ github.event.inputs.working_directory }}

      # 5️⃣ Terraform Plan
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ${{ github.workspace }}/{{ github.event.inputs.working_directory }}

  terraform-apply:
    needs: terraform
    runs-on: [self-hosted, Windows]
    environment:
      name: dev


    steps:
      # ✅ Manual Approval Step
      - name: Wait for Manual Approval
        uses: hmarr/auto-approve-action@v2
        with:
          approve: false  # false means it will pause for manual approval

      # 6️⃣ Terraform Apply
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: ${{ github.workspace }}/{{ github.event.inputs.working_directory }}
