
name: "Parrix infra pipeline"

on:
  workflow_dispatch:
    inputs:
      working_directory:
        description: "Path to Terraform working directory"
        required: true
        default: "rg"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform on Window Self-Host Runner
    runs-on: [self-hosted, Windows]

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_IN_AUTOMATION: true
      TF_INPUT: false
      WORK_DIR: ${{ github.event.inputs.working_directory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Verify working directory
        shell: pwsh
        run: |
          Get-ChildItem "${{ github.workspace }}"

      - name: Terraform Init
        id: init
        shell: pwsh
        working-directory: ${{ github.workspace }}${{ '/' }}${{ github.event.inputs.working_directory }}
        run: terraform init

      - name: Terraform Validate
        id: validate
        shell: pwsh
        working-directory: ${{ github.workspace }}${{ '/' }}${{ github.event.inputs.working_directory }}
        run: terraform validate 

      - name: Terraform Plan
        id: plan
        shell: pwsh
        working-directory: ${{ github.workspace }}${{ '/' }}${{ github.event.inputs.working_directory }}
        run: terraform plan

  manual_validation:
    name: Manual Validation (Environment Approval)
    needs: terraform
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Awaiting Approval
        run: echo "Waiting for environment approval to proceed to apply..."

  apply:
    name: Terraform Apply (Approved)
    needs: manual_validation
    runs-on: [self-hosted, Windows]

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_IN_AUTOMATION: true
      TF_INPUT: false
      WORK_DIR: ${{ github.event.inputs.working_directory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Terraform Init
        id: init
        shell: pwsh
        working-directory: ${{ github.workspace }}${{ '/' }}${{ github.event.inputs.working_directory }}
        run: terraform init

      - name: Terraform Apply
        id: apply
        shell: pwsh
        working-directory: ${{ github.workspace }}${{ '/' }}${{ github.event.inputs.working_directory }}
        run: terraform apply -auto-approve
